//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poseshchaemost
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB : DbContext
    {
        private static DB bd;
        public DB()
            : base("name=DB")
        {
        }
        public static DB GetBD()
        {
            if (bd == null)
            {
                bd = new DB();
            }
            return bd;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Prokhod> Prokhods { get; set; }
        public DbSet<Sotrudnik> Sotrudniks { get; set; }
    }
}
