//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poseshchaemost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prokhod
    {
        public int id_prokhod { get; set; }
        public int sotrudnik { get; set; }
        public System.DateTime data { get; set; }
    
        public virtual Sotrudnik Sotrudnik1 { get; set; }
    }
}
