//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poseshchaemost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        public Sotrudnik()
        {
            this.Prokhod = new HashSet<Prokhod>();
        }
    
        public int id_sotrudnik { get; set; }
        public string familiya { get; set; }
        public string imya { get; set; }
        public string otchestvo { get; set; }
        public string cart { get; set; }
        public int kurator { get; set; }
        public byte[] foto { get; set; }
    
        public virtual ICollection<Prokhod> Prokhod { get; set; }
    }
}
